## This is the labgrid-exporter user-configuration.
## Labgrid uses jinja2 templating for its config file.
## This file is included from configuration.yaml by a jinja2 include and can
## set some variables evaluated in configuration.yaml.

## The userconfig.yaml file is migrated between rauc installs.
## Use cp /etc/labgrid/userconfig.yaml.default /etc/labgrid/userconfig.yaml
## to go back to the most recent defaults.


## Add your own exports here.

## Example for using an external USB to serial adapter and matching based
## on its serial number (instead of e.g. an USB path as below):
##example-group1-remote:
##  location: example-location-1-remote
##  USBSerialPort:
##    match:
##      'ID_SERIAL_SHORT': 'FTA8E2HP'
##    speed: 115200

## Example for using a custom baud rate of 1M baud instead of the
## 115200 baud default on the box connector:
##{% serial.baud = 1000000 %}

## Example for using an USB hub.
## The usb.ports variable is used in configuration.yaml to set up common
## USB peripheral matches on all listed ports.
## This snippet removes direct matches on port three of the TAC and instead
## matches on each port of a hub connected to port three:
##{% set usb.ports = [
##        ('1',   'platform-5800d000.usb-usb-0:1.1'),
##        ('2',   'platform-5800d000.usb-usb-0:1.2'),
##        ('3-1', 'platform-5800d000.usb-usb-0:1.3.1'),
##        ('3-2', 'platform-5800d000.usb-usb-0:1.3.2'),
##        ('3-3', 'platform-5800d000.usb-usb-0:1.3.3'),
##        ('3-4', 'platform-5800d000.usb-usb-0:1.3.4')] %}
