name: codespell

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  codespell:
    name: codespell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python3 -m pip install codespell
      - run: codespell
